// packages/jxion-react/src/components/Layout.tsx
import React from "react";
import styles from "@jxion/design/src/components/UstadLayout.module.scss";

interface LayoutProps {
  params: {
    lang: string;
    theme: string;
  };
  children: React.ReactNode;
}

export const Layout: React.FC<LayoutProps> = ({ params, children }) => {
  return (
    <div className={styles.layout} data-lang={params.lang} data-theme={params.theme}>
      {children}
    </div>
  );
};

export default Layout;

// packages/jxion-vue/src/components/Layout.vue
<template>
  <div class="layout" :data-lang="params.lang" :data-theme="params.theme">
    <slot />
  </div>
</template>

<script setup lang="ts">
import styles from "@jxion/design/src/components/layout.module.scss";

interface LayoutProps {
  params: {
    lang: string;
    theme: string;
  };
}

defineProps<LayoutProps>();
</script>

<style scoped>
@import "@jxion/design/src/components/layout.module.scss";
</style>
