// packages/jxion-vue/src/components/CTA.vue
<template>
  <div v-html="renderedTemplate"></div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import styles from "@jxion/design/src/components/cta.module.scss";
import { ctaTemplate, TemplateRenderer } from "@jxion/core";

interface CTAProps {
  primaryText: string;
  secondaryText?: string;
  onPrimaryClick?: () => void;
  onSecondaryClick?: () => void;
  testId?: string;
}

const props = withDefaults(defineProps<CTAProps>(), {
  secondaryText: "",
  onPrimaryClick: undefined,
  onSecondaryClick: undefined,
  testId: "cta",
});

// Prepare variables for template rendering
const variables = computed(() => ({
  primaryText: props.primaryText,
  secondaryText: props.secondaryText,
  onPrimaryClick: props.onPrimaryClick ? "onPrimaryClick" : "",
  onSecondaryClick: props.onSecondaryClick ? "onSecondaryClick" : "",
  testId: props.testId,
}));

// Render template with variables
const renderedTemplate = computed(() => {
  let rendered = TemplateRenderer.render({ 
    template: ctaTemplate.html, 
    variables: variables.value 
  });

  // Map CSS module classes
  Object.keys(styles).forEach((className) => {
    const regex = new RegExp(`class="([^"]*\\b${className}\\b[^"]*)"`, "g");
    rendered = rendered.replace(regex, (match, classList) => {
      const mappedClasses = classList
        .split(" ")
        .map((cls: string) => styles[cls] || cls)
        .join(" ");
      return `class="${mappedClasses}"`;
    });
  });

  return rendered;
});
</script>

<style scoped>
@import "@jxion/design/src/components/cta.module.scss";
</style>

// packages/jxion-react/src/components/CTA.tsx
import React from "react";
import styles from "@jxion/design/src/components/cta.module.scss";
import { ctaTemplate, TemplateRenderer } from "@jxion/core";

/**
 * CTA Component - React Implementation
 *
 * Uses:
 * - HTML template from @jxion-core (ctaTemplate.html)
 * - SCSS styles from @jxion-design
 * - TemplateRenderer for dynamic rendering
 */
export interface CTAProps {
  primaryText: string;
  secondaryText?: string;
  variant?: string;
  onPrimaryClick?: () => void;
  onSecondaryClick?: () => void;
  testId?: string;
}

export const CTA: React.FC<CTAProps> = ({
  primaryText,
  secondaryText,
  variant = "",
  onPrimaryClick,
  onSecondaryClick,
  testId = "cta",
}) => {
  // Get the base HTML template from @jxion-core
  const baseTemplate = ctaTemplate.html;

  // Prepare variables for template rendering
  const variables = {
    variant,
    primaryText,
    secondaryText: secondaryText || "",
    onPrimaryClick: onPrimaryClick ? "onPrimaryClick" : "",
    onSecondaryClick: onSecondaryClick ? "onSecondaryClick" : "",
    testId,
  };

  // Render template with variables
  let rendered = TemplateRenderer.render({ template: baseTemplate, variables });

  // Map CSS module classes
  Object.keys(styles).forEach((className) => {
    const regex = new RegExp(`class="([^"]*\\b${className}\\b[^"]*)"`, "g");
    rendered = rendered.replace(regex, (match, classList) => {
      const mappedClasses = classList
        .split(" ")
        .map((cls: string) => styles[cls] || cls)
        .join(" ");
      return `class="${mappedClasses}"`;
    });
  });

  // Set up click handlers for template
  React.useEffect(() => {
    if (onPrimaryClick) {
      (window as any).ctaPrimaryClick = onPrimaryClick;
    }
    if (onSecondaryClick) {
      (window as any).ctaSecondaryClick = onSecondaryClick;
    }
  }, [onPrimaryClick, onSecondaryClick]);

  return (
    <div
      dangerouslySetInnerHTML={{
        __html: rendered
          .replace(/onclick="onPrimaryClick"/g, 'onclick="window.ctaPrimaryClick"')
          .replace(/onclick="onSecondaryClick"/g, 'onclick="window.ctaSecondaryClick"'),
      }}
    />
  );
};

export default CTA;
